### ISSUE TITLE
Templates should compile

### ISSUE THREAD

**Issue by cabo** [ietf-authors/rfcxml-templates-and-schemas#5]
Wouldn't it be useful to be able to process these template files with xml2rfc?

**Comment by cabo** [comment]
https://trac.ietf.org/trac/xml2rfc/ticket/707

**Comment by JayDaley** [comment]
Those were checked with xml2rfc so I'm not sure where that error entered.  I will investigate.

**Comment by arusso-rpc** [comment]
FWIW, to get the standard template to generate output on https://author-tools.ietf.org, I changed it to ```<date />``` and commented out the ```<figure>``` that points to diagram.svg (updated file is [here](https://www.rfc-editor.org/v3test/sample4.xml)). (A different approach would be to point to a sample svg file at a full URL.)

Here are the errors encountered before making those changes:
```xml2rfc error: Expected to have the current year when month is missing, but found '2021'```

then this for the "[REPLACE]":
```xml2rfc error: Found disallowed shell meta-characters in the src='file:...' attribute```

then this for the file
```xml2rfc error: Expected an src= file at '/usr/[...]/diagram.svg', but no such file exists```
